# Site settings
title: "Lara Martín"
email: lara.martin.carretero@gmail.com
description: "Android Developer"
baseurl: ""
url: "http://laramartin.eu"
title_description: "Android Developer based in Berlin"
title_image: assets/profile.jpg
thumbnail: assets/lara_white_tiny.png
# google_analytics: "UA-74035075-1"
# disqus_account: cartenoire
github_repository: https://github.com/laramartin/laramartin.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: lariki
github_username:  laramartin
medium: laramartin
# instagram_username:
# reddit_username:
linkedin_link: https://www.linkedin.com/in/laramartincarretero/
# google_plus_link:
# stackoverflow_link:
# xing_link:
# facebook_link:

# Footer
footer_left: "Lara Martín 2017"
# footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
